config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'about', to: 'misc#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :profiles
    end
  end
  resources :machines, only: [:show]
  resources :relationship_of_follows, only: [:create, :destroy]
  resources :videoposts, only: [:new, :create, :destroy]
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship_of_follow.rb
class RelationshipOfFollow < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    validates :introduce, length: { maximum: 100}
    has_secure_password               
    
    mount_uploader :img, ImgUploader
    mount_uploader :picture, PictureUploader
    
    has_many :relationship_of_follows
    has_many :followings, through: :relationship_of_follows, source: :follow
    has_many :reverses_of_relationship_of_follows, class_name: 'RelationshipOfFollow', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship_of_follows, source: :user
    has_many :videoposts
    
    def follow(other_user)
        unless self == other_user
            self.relationship_of_follows.find_or_create_by(follow_id: other_user.id)
        end
    end
    
    def unfollow(other_user)
        relationship_of_follow = self.relationship_of_follows.find_by(follow_id: other_user.id)
        relationship_of_follow.destroy if relationship_of_follow
    end
    
    def following?(other_user)
        self.followings.include?(other_user)
    end

end

app/models/videopost.rb
class Videopost < ApplicationRecord
  belongs_to :user
  
  validates :youtube_title, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
        @count_followings = user.followings.count
        @count_followers = user.followers.count
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def show
    @user = User.find(params[:id])
    counts(@user)
  end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/relationship_of_follows_controller.rb
class RelationshipOfFollowsController < ApplicationController
  before_action :require_user_logged_in
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォロー を解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
     @user = User.find_by(email: email)
     if @user && @user.authenticate(password)
       session[:user_id] = @user.id
       return true
     else
       return false
     end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.order(id: :desc).page(params[:page]).per(15)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @videoposts = @user.videoposts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました。"
      redirect_to @user
    else
      flash[:danger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])
    
    unless @user == current_user
      redirect_to root_url
    end
    
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to profiles_user_path(@user)
    else
      flash.now[:danger] = "プロフィールは更新されませんでした。"
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def profiles
    @user = User.find(params[:id])
  end
  
  private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :genre, :phonenumber, :adress, :img, :placeofactivity, :hobby, :sex, :camera, :lens, :app )
end

end

app/controllers/videoposts_controller.rb
class VideopostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  def show
    
  end
  
  def new
    if logged_in?
       @videopost = current_user.videoposts.build
    end
  end
  
  def create
    @videopost = current_user.videoposts.build(videopost_params)
    if @videopost.save
      flash[:success] = 'ポートフォリオを更新しました'
      redirect_to user_path(current_user)
    else
      flash[:danger] = 'ポートフォリオの更新に失敗しました。'
      render :new
    end
  end

  def destroy
    @videopost.destroy
    flash[:success] = 'ポートフォリオを削除しました。'
    redirect_back(fallback_location: user_path(current_user))
  end
  
  private
  
  def videopost_params
    params.require(:videopost).permit(:youtube_title, :youtube_url)
  end
  
  def correct_user
    @videopost = current_user.videoposts.find_by(id: params[:id])
    unless @videopost
      redirect_to root_url
      
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">VideoPlus</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
           <li class='nav-item'><%= link_to 'VideoPlusについて', about_path, class: 'nav-link' %></li>
           <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
           <li class='nav-item dropdown'>
             <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown'><%= current_user.name %></a>
             <ul class='dropdown-menu dropdown-menu-right'>
               <li class='dropdown-item'><%= link_to 'My page', user_path(current_user) %></li>
               <li class='dropdown-item'><%= link_to 'プロフィール編集', edit_user_path(current_user) %></li>
               <li class='dropdown-item'><%= link_to 'ポートフォリオ編集', new_videopost_path %></li>
               <li class="dropdown-divider"></li>
               <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
             </ul>
           </li>
        <% else %>
        　 <li class='nav-item'><%= link_to 'VideoPlusについて', about_path, class: 'nav-link' %></li>
           <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
           <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/machines/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= @user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <% if @user.img? %>
           <%= image_tag @user.img.to_s,class:'img-fluid',src:'' %>
        <% else %>
           <image src="/assets/default.png" class="icon" alt="ユーザーアイコン">
        <% end%>
        
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(profiles_user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">ポートフォリオ</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'machines/machine_table', user: @user %>
  </div>
</div>

app/views/misc/about.html.erb
<div class='story-title'>
    <div class='container'>
        <h3>VideoPlusについて</h3>
    </div>
</div>
<div class='container'>
    <div class='row'>
        <div class='col-md-10 col-md-offset-1'>
            <br>
            <h3 class='text-center' style='font-weight: bold;'>個人店舗は集客するのが難しい?</h3>
            <h6 class='story-paragraph'>あなたはこんな悩みを持ったことはありませんか？
            <br>
            </h6>
            <h6>
                <i class="fas fa-check-circle"></i>
                グルメサイトに掲載して集客したいけど、莫大なコストがかかってしまう。
            </h6>
            <h6>
                <i class="fas fa-check-circle"></i>
                チラシ広告を出しているのにお客さんがあまり増えない。
            </h6>
            <h6>
                <i class="fas fa-check-circle"></i>
                クーポンやサービスもたくさんあるのにリピーターが増えない。
            </h6>
            <h5 class='story-paragraph text-center' style= 'font-weight: bold; text-decoration: underline;'>
                その原因はあなたがユーザーの気持ちになって考えられていないからです。
            </h5>
            <br>
            <h6 class='story-paragraph'>
                実は私の実家の飲食店がそうでした。
                <br>
                少しだけ私のお話しをしますと、
                <br>
                実家が飲食店を経営しており、それは30年近く同じ場所で営業していました。
                <br>
                私が小さい頃は毎日、お店に列ができていました。
                <br>
                しかし、都市開発やインターネットの普及により、
                <br>
                あらゆるお店にお客さんが分散しはじめました。
                <br>
                大手の飲食店はグルメサイトやSNSを活用して集客をする一方で
                <br>
                これまでは口コミや雑誌などでしか集客してこなかった個人店舗は
                <br>
                集客にかなり苦労するようになりました。
            </h6>
            <br>
            <br>
            <h3 class='text-center' style='font-weight: bold;'>
                お店と動画クリエーターをつなぐマッチングアプリ『VideoPlus』
            </h3>
            <h6 class='story-paragraph'>
                グルメサイトはシステム上、お金をかければかけるほど上位に掲載されます。<br>
                つまり、オークションマーケティングです。<br>
                個人店舗が大手飲食店に資金力で勝負するのは不可能です。<br>
                なので個人店舗は資金力ではなく<strong style='text-decoration: underline;'>SNSを活用したクオリティで勝負する必要があります。</strong><br>
                しかしながら、今までチラシで集客していた人がSNSを活用するのはかなりのハードルであり、
            　　<br>
                それを実家の店舗は活用できずにいました。
            　　<br>
                そんなときに旅行に行っては撮影をして自分で編集し、それをSNSでシェアしていた私は、
            　　<br>
                お店の動画を作成することを思いつきました。
                <br>
                動画は写真よりも情報量が5000倍あると言われており、<br>
                短時間でより多くの情報をユーザーに届けることができます。<br>
                SNSを導入してからは、それをみて来たという人が増え、もっと多くの個人店舗がSNSの活用ができるように<br>
                『VideoPlus』は開発されました。
            </h6>
            <h3 class='text-center' style='font-weight: bold;'>
                あらゆるジャンルの動画クリエーターが登録
            </h3>
            <h6 class='story-paragraph'>
                飲食店以外にもパーソナルトレーナーや、ヨガ講師なども個人で集客する必要があります。<br>
                そこでクリエーターは自身が得意とするジャンルや、ポートフォリオを登録することで、<br>
                ミスマッチが起こることなく、繋がることができます。
                <br>
            </h6>
            <br>
            <br>
            <h5 class='story-paragraph text-center' style='font-weight: bold;'>
                あなたのお店にビデオ広告を追加しませんか？<br>
                VideoPlusはあなたにとって最適な動画を作成できるクリエーターを紹介します。<br>
                さぁ、はじめよう。
            </h5>
            <div class="register-section text-center">
              <%= link_to '登録する', signup_path, class: 'btn btn-info' %>
            </div>
        </div>
    </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <body class='main-img'>
  
</body>
<div class="cover">
  <div class='full-bg-img'>
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-7 col-sm-12 text-center">
            <div class="brand">
              <h1 class='main_font text-light' style='font-weight: bold;'>VideoPlusで広告を</h1>
              <br>
              <h3 class='text-light'>お店とクリエーターをつなぐ<br>動画制作マッチングアプリ</h3>
              <br>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<br>
<br>
<div class='service-section'>
  <h1 class='text-center'>簡単３ステップ</h1>
  <hr color='black'>
  <br>
  <br>
  <br>
   <div class='container'>
     <div class='row'>
       <div class="col-md-4 pc">
            <h3 style="height: 90px;">
              <img src='/assets/pc_icom.png' alt='パソコン' class="material-icons md-36" widht='50px' height='50px'>
              <p class='three-titles' style=font-weight:bold;>簡単登録</p>
            </h3>
            <p class="service-summary content">
              簡単な個人情報を登録するだけ！１分で登録して、すぐにクリエーターを探せます！
            </p>
        </div>
        <div class="col-md-4 man">
            <h3 style="height: 90px;">
              <img src='/assets/man_icom.png' alt='クリエーター' class="material-icons md-36" widht='50px' height='50px'>
              <p class='three-titles' style=font-weight:bold;>クリエーターを探す</p>
            </h3>
            <p class="service-summary content">
              あなたの求めるジャンルを得意とするクリエーターを探すことができます！クリエーターは得意なジャンルとポートフォリオを登録しているので、
              お気に入りのテイストの動画が作れるクリエーターをフォロー。そしてInstagramからメッセージを送ってみよう！
            </p>
        </div>
        <div class="col-md-4">
            <h3 style="height: 90px;">
              <img src='/assets/camera_icom.png' alt='カメラ' class="material-icons md-36" widht='50px' height='50px'>
              <p class='three-titles' style=font-weight:bold;>撮影開始</p>
            </h3>
            <p class="service-summary content">
              Instagramでやりとりをしてマッチングが成立したら、実際に撮影開始です！
            </p>
        </div>
     </div>
   </div>
   <br>
   <br>
  
</div>





<% else %>
<body class='main-img'>
  
</body>
<div class="cover">
  <div class='full-bg-img'>
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-7 col-sm-12 text-center">
            <div class="brand">
              <h1 class='main_font text-light' style='font-weight: bold;'>VideoPlusで広告を</h1>
              <br>
              <h3 class='text-light'>お店とクリエーターをつなぐ<br>動画制作マッチングアプリ</h3>
              <br>
              <%= link_to '新規登録', signup_path, class: 'btn btn-block btn-light' %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<br>
<br>
<div class='service-section'>
  <h1 class='text-center'>簡単３ステップ</h1>
  <hr color='black'>
  <br>
  <br>
  <br>
   <div class='container'>
     <div class='row'>
       <div class="col-md-4 pc">
            <h3 style="height: 90px;">
              <img src='/assets/pc_icom.png' alt='パソコン' class="material-icons md-36" widht='50px' height='50px'>
              <p>簡単登録</p>
            </h3>
            <p class="service-summary content">
              簡単な個人情報を登録するだけ！１分で登録して、すぐにクリエーターを探せます！
            </p>
        </div>
        <div class="col-md-4 man">
            <h3 style="height: 90px;">
              <img src='/assets/man_icom.png' alt='クリエーター' class="material-icons md-36" widht='50px' height='50px'>
              <p>クリエーターを探す</p>
            </h3>
            <p class="service-summary content">
              あなたの求めるジャンルを得意とするクリエーターを探すことができます！クリエーターは得意なジャンルとポートフォリオを登録しているので、
              お気に入りのテイストの動画が作れるクリエーターをフォロー。そしてInstagramからメッセージを送ってみよう！
            </p>
        </div>
        <div class="col-md-4">
            <h3 style="height: 90px;">
              <img src='/assets/camera_icom.png' alt='カメラ' class="material-icons md-36" widht='50px' height='50px'>
              <p>撮影開始</p>
            </h3>
            <p class="service-summary content">
              Instagramでやりとりをしてマッチングが成立したら、実際に撮影開始です！
            </p>
        </div>
     </div>
   </div>
   <br>
   <br>
   <div class='text-center'>
      <%= link_to '新規登録', signup_path, class: 'btn btn-lg btn-info' %>
   </div>
</div>

<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= @user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <% if @user.img? %>
           <%= image_tag @user.img.to_s,class:'img-fluid',src:'' %>
        <% else %>
           <image src="/assets/default.png" class="icon" alt="ユーザーアイコン">
        <% end%>
        
      </div>
    </div>
    <%= render 'relationship_of_follows/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(profiles_user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">ポートフォリオ</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
    </ul>
    <br>
    <div class='text-left'>
      <h2>フォロワー一覧</h2>
    </div>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= @user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <% if @user.img? %>
           <%= image_tag @user.img.to_s,class:'img-fluid',src:'' %>
        <% else %>
           <image src="/assets/default.png" class="icon" alt="ユーザーアイコン">
        <% end%>
        
      </div>
    </div>
    <%= render 'relationship_of_follows/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(profiles_user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">ポートフォリオ</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
    </ul>
    <br>
    <div class='text-left'>
      <h2>フォロー一覧</h2>
    </div>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/profiles.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= @user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <% if @user.img? %>
           <%= image_tag @user.img.to_s,class:'img-fluid',src:'' %>
        <% else %>
           <image src="/assets/default.png" class="icon" alt="ユーザーアイコン">
        <% end%>
        
      </div>
    </div>
    <%= render 'relationship_of_follows/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(profiles_user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">ポートフォリオ</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users/profile_table', user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= @user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <% if @user.img? %>
           <%= image_tag @user.img.to_s,class:'img-fluid',src:'' %>
        <% else %>
           <image src="/assets/default.png" class="icon" alt="ユーザーアイコン">
        <% end%>
        
      </div>
    </div>
    <%= render 'relationship_of_follows/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= profiles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(profiles_user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">ポートフォリオ</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'videoposts/videoposts', videoposts: @videoposts %>
  </div>
</div>

app/views/users/videoposts.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center"><%= current_user.name %></h3>
      </div>
      <div class="card-body id='user_image">
        <%= image_tag current_user.img.to_s,class:'img-fluid',src:'' %>
      </div>
    </div>
    <%= render 'relationship_of_follows/follow_button', user: current_user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= machine_path(@user) %>" class="nav-link <%= 'active' if current_page?(machine_path(@user)) %>">使用機材</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー <span class='badge badge-secondary'><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class='badge badge-secondary'><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="#" class="nav-link">メッセージ</a></li>
    </ul>
    <%= render 'videoposts/videoposts', videoposts: @videoposts %>
  </div>
</div>